dist: trusty
sudo: required
language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo apt-get install thrift-compiler

script:
  - codecov

after_success:
  - ./gradlew dockerize
