dist: trusty
sudo: required
language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - sudo apt-get install thrift-compiler

script:
  - ./gradlew jacocoTestReport

after_success:
  - ./gradlew dockerize -Ptravis
  - cd server && bash <(curl -s https://codecov.io/bash)
