codecov:
  branch: master

coverage:
  precision: 3
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: 0%
    patch: no

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default